# Generated by Django 5.2.15 on 2026-06-19 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caseembedding',
            name='clean_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='caseembedding',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
