# Generated by Django 5.2.15 on 2026-06-23 05:31

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_add_year_and_cleantext_to_caseembedding'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='caseembedding',
            index=pgvector.django.indexes.IvfflatIndex(fields=['embedding'], lists=100, name='embedding_ivfflat_idx', opclasses=['vector_cosine_ops']),
        ),
    ]
